name: |
  Get Ref Info
description: |
  Returns information for the given ref

inputs:
  github_token:
    description: |
      Github token used for API calls. Required scope - 'contents: read'
    default: ${{ github.token }}

  owner:
    description: |
      Owner of the repository
    default: ${{ github.repository_owner }}

  repo:
    description: |
      Repository name
    default: ${{ github.event.repository.name }}

  ref:
    description: |
      Target ref name
    required: true

outputs:
  exists:
    description: |
      Ref exists
    value: ${{ steps.get-ref.outputs.exists }}

  ref:
    description: |
      Ref name
    value: ${{ steps.get-ref.outputs.ref }}

  sha:
    description: |
      Ref SHA
    value: ${{ steps.get-ref.outputs.sha }}

  type:
    description: |
      Ref type
    value: ${{ steps.get-ref.outputs.type }}

runs:
  using: "composite"
  steps:
    - name: Get ref
      id: get-ref
      shell: bash
      run: |
        # Getting tag ref information
        owner=${{ inputs.owner }}
        repo=${{ inputs.repo }}
        ref=${{ inputs.ref }}

        set +e
        response=$( \
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/$owner/$repo/git/ref/$ref \
        )
        exit_code=$?
        set -e

        echo "response=${response}"
        echo "exit_code=${exit_code}"

        if [[ $exit_code -ne 0 ]]; then
          response_code=$(echo $response | jq -r '.status')
          if [[ "$response_code" == "404" ]]; then
            echo "exists=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "$response"
          exit 1
        fi

        echo "exists=true" >> $GITHUB_OUTPUT
        echo "ref=${ref}" >> $GITHUB_OUTPUT
        echo "sha=$(echo $response | jq -r '.object.sha')" >> $GITHUB_OUTPUT
        echo "type=$(echo $response | jq -r '.object.type')" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ inputs.github_token }}

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: "message-square"
  color: "gray-dark"
