name: |
  Get Ref Info
description: |
  Returns information for the given ref

branding:
  icon: "message-square"
  color: "gray-dark"

inputs:
  github_token:
    description: |
      Github token used for API calls. Required scope - 'contents: read'
    default: ${{ github.token }}

  owner:
    description: |
      Owner of the repository
    default: ${{ github.repository_owner }}

  repo:
    description: |
      Repository name
    default: ${{ github.event.repository.name }}

  ref:
    description: |
      Target ref name
    required: true

outputs:
  exists:
    description: |
      Ref exists
    value: ${{ steps.run.outputs.exists }}

  ref:
    description: |
      Ref name
    value: ${{ steps.run.outputs.ref }}

  sha:
    description: |
      Ref SHA
    value: ${{ steps.run.outputs.sha }}

  type:
    description: |
      Ref type
    value: ${{ steps.run.outputs.type }}

runs:
  using: "composite"
  steps:
    - name: Run
      id: run
      shell: bash
      run: |
        ${{ github.action_path }}/src/main.sh
      env:
        OWNER: ${{ inputs.owner }}
        REPO: ${{ inputs.repo }}
        REF: ${{ inputs.ref }}
        GH_TOKEN: ${{ inputs.github_token }}
