name: "Setup Environment"
description: "Setting environment for the project"

inputs:
  task-version:
    description: "Task version"
    required: true
    default: "3.33.1"
  task-enabled:
    description: "Task enabled"
    required: true
    default: "true"
  zizmor-version:
    description: "Zizmor version"
    required: true
    default: "1.0.1"
  zizmor-enabled:
    description: "Zizmor enabled"
    required: true
    default: "false"
  shellcheck-version:
    description: "Shellcheck version"
    required: true
    default: "0.9.0-1"
  shellcheck-enabled:
    description: "Shellcheck enabled"
    required: true
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup Task
      if: ${{ inputs.task-enabled == 'true' }}
      uses: arduino/setup-task@v2.0.0
      with:
        version: ${{ inputs.task-version }}

    - name: Setup Zizmor
      if: ${{ inputs.zizmor-enabled == 'true' }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install "zizmor==${ZIZMOR_VERSION}"
      env:
        ZIZMOR_VERSION: ${{ inputs.zizmor-version }}

    - name: Setup Shellcheck
      if: ${{ inputs.shellcheck-enabled == 'true' }}
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y "shellcheck=${SHELLCHECK_VERSION}"
      env:
        SHELLCHECK_VERSION: ${{ inputs.shellcheck-version }}
